name: Test disko

on:
  push:
    branches: [ "ygal" ]

jobs:
  TestStatistic:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up kubeconfig
        run: | 
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config

    - name: Port forward Kubernetes API
      run: nohup kubectl port-forward --address 0.0.0.0 svc/kubernetes 44781:443 &

      - name: Installing requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run test copy images
        run: |
          pytest test_statistic.py
          echo "✅ Statistic test was completed successfully!"

  TestCopyImages:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installing requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run test copy images
        run: |
          pytest test_copy_image.py
          echo "✅ Copy images test was completed successfully!"
          # exit_code=$?
          # if [ $exit_code -eq "0" ]; then
          #   echo "✅ Copy images test was completed successfully!"
          # else
          #   echo "❌ Copy images test was failed!"
          # fi