name: Test disko

on:
  push:
    branches: [ "ygal" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installing requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run test copy images
        run: |
          pytest test_copy_image.py
          echo $?
          
